In [3]:
import sys

sys.path.append('../')
import mustaching as ms


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Load transactions

In [8]:
# Invent some sample transactions.
transactions = ms.create_transactions('2017-01-01', '2017-12-31')

# Alternatively, upload your own transactions as say 'my_transactions.csv' 
#transactions = ms.read_transactions('my_transactions.csv')

transactions.head(10)

                 date  amount description       comment     category
0 2017-01-01 00:00:00     -63     0x8b6d4  0x6bb63ec0ad   healthcare
1 2017-01-01 12:00:00     -15     0xc8a78  0xf624af9460   healthcare
2 2017-01-02 00:00:00      68     0x28ce4  0x739cef7a8d  programming
3 2017-01-02 12:00:00     -51     0x634cb  0xa0b9456821      shelter
4 2017-01-03 00:00:00      52     0xdd924  0xbd3c0cd239  programming
5 2017-01-03 12:00:00     -69     0xf7912  0x389d3523a5      shelter
6 2017-01-04 00:00:00      32     0x836b4  0x6d1e76ddb6  programming
7 2017-01-04 12:00:00      81     0x9c859  0x7087098099  programming
8 2017-01-05 00:00:00     -54     0x234c7  0x910bced5cc    transport
9 2017-01-05 12:00:00      -9     0x659f3  0xb03ee76e65      shelter

In [10]:
import io

ms.read_transactions(io.StringIO(transactions.to_csv(index=False)))

                   date  amount description     category       comment
0   2017-01-01 00:00:00   -63.0     0x8b6d4   healthcare  0x6bb63ec0ad
1   2017-01-01 12:00:00   -15.0     0xc8a78   healthcare  0xf624af9460
2   2017-01-02 00:00:00    68.0     0x28ce4  programming  0x739cef7a8d
3   2017-01-02 12:00:00   -51.0     0x634cb      shelter  0xa0b9456821
4   2017-01-03 00:00:00    52.0     0xdd924  programming  0xbd3c0cd239
..                  ...     ...         ...          ...           ...
724 2017-12-29 00:00:00    73.0     0x6504e  programming  0x34cd33fc64
725 2017-12-29 12:00:00   -44.0     0xc4295    transport  0x8c05ca596a
726 2017-12-30 00:00:00    34.0     0x4af8f        reiki  0x7771dd84d0
727 2017-12-30 12:00:00   -29.0     0x48279      shelter  0x839c7b61d4
728 2017-12-31 00:00:00    11.0     0x52525  programming  0x55fc7f6359

[729 rows x 5 columns]

# Summarize transactions and plot

In [3]:
# Summarize over entire period by category
s1 = ms.summarize(transactions, by_category=True)
s1

,date,category,income,expense,balance,savings_pc_for_period,spending_pc_for_period,spending_pc_for_period_and_category,income_pc_for_period_and_category,expense_pc_for_period_and_category,daily_avg,weekly_avg,monthly_avg,yearly_avg
0,2017-01-01,food,0,1432,8303,42.34,57.66,7.30,0.00,12.66,-3.92,-27.46,-119.33,-1432.0
1,2017-01-01,healthcare,0,1934,8303,42.34,57.66,9.86,0.00,17.10,-5.30,-37.09,-161.17,-1934.0
2,2017-01-01,investing,4938,0,8303,42.34,57.66,0.00,25.18,0.00,13.53,94.70,411.50,4938.0
3,2017-01-01,programming,9273,0,8303,42.34,57.66,0.00,47.28,0.00,25.41,177.84,772.75,9273.0
4,2017-01-01,reiki,5400,0,8303,42.34,57.66,0.00,27.54,0.00,14.79,103.56,450.00,5400.0
5,2017-01-01,shelter,0,4210,8303,42.34,57.66,21.47,0.00,37.23,-11.53,-80.74,-350.83,-4210.0
6,2017-01-01,soil testing,0,1931,8303,42.34,57.66,9.85,0.00,17.08,-5.29,-37.03,-160.92,-1931.0
7,2017-01-01,transport,0,1801,8303,42.34,57.66,9.18,0.00,15.93,-4.93,-34.54,-150.08,-1801.0

In [10]:
ms.plot(s1)

In [5]:
# Summarize by month start
s2 = ms.summarize(transactions, freq='Q', by_category=True)
s2

/home/araichev/mustaching/mustaching/main.py:320: RuntimeWarning: divide by zero encountered in double_scalars
  100
/home/araichev/mustaching/mustaching/main.py:325: RuntimeWarning: divide by zero encountered in double_scalars
  spending_pc = 100 * group["expense"].sum() / group["income"].sum()

,date,category,income,expense,balance,savings_pc_for_period,spending_pc_for_period,spending_pc_for_period_and_category,income_pc_for_period_and_category,expense_pc_for_period_and_category
0,2016-12-31,food,0.0,577.0,2019.0,40.58,59.42,11.60,0.00,19.52
1,2016-12-31,healthcare,0.0,489.0,2019.0,40.58,59.42,9.83,0.00,16.54
2,2016-12-31,investing,1129.0,0.0,2019.0,40.58,59.42,0.00,22.69,0.00
3,2016-12-31,programming,2420.0,0.0,2019.0,40.58,59.42,0.00,48.64,0.00
4,2016-12-31,reiki,1426.0,0.0,2019.0,40.58,59.42,0.00,28.66,0.00
5,2016-12-31,shelter,0.0,1089.0,2019.0,40.58,59.42,21.89,0.00,36.84
6,2016-12-31,soil testing,0.0,251.0,2019.0,40.58,59.42,5.05,0.00,8.49
7,2016-12-31,transport,0.0,550.0,2019.0,40.58,59.42,11.06,0.00,18.61
8,2017-03-31,food,0.0,173.0,4022.0,43.95,56.05,3.80,0.00,6.77
9,2017-03-31,healthcare,0.0,658.0,4022.0,43.95,56.05,14.44,0.00,25.76
10,2017-03-31,investing,1282.0,0.0,4022.0,43.95,56.05,0.00,28.13,0.00
11,2017-03-31,programming,1960.0,0.0,4022.0,43.95,56.05,0.00,43.01,0.00
12,2017-03-31,reiki,1315.0,0.0,4022.0,43.95,56.05,0.00,28.86,0.00
13,2017-03-31,shelter,0.0,951.0,4022.0,43.95,56.05,20.87,0.00,37.24
14,2017-03-31,soil testing,0.0,404.0,4022.0,43.95,56.05,8.87,0.00,15.82
15,2017-03-31,transport,0.0,368.0,4022.0,43.95,56.05,8.08,0.00,14.41
16,2017-06-30,food,0.0,183.0,6792.0,51.43,48.57,3.40,0.00,7.00
17,2017-06-30,healthcare,0.0,310.0,6792.0,51.43,48.57,5.76,0.00,11.85
18,2017-06-30,investing,1235.0,0.0,6792.0,51.43,48.57,0.00,22.93,0.00
19,2017-06-30,programming,2553.0,0.0,6792.0,51.43,48.57,0.00,47.40,0.00
20,2017-06-30,reiki,1598.0,0.0,6792.0,51.43,48.57,0.00,29.67,0.00
21,2017-06-30,shelter,0.0,992.0,6792.0,51.43,48.57,18.42,0.00,37.92
22,2017-06-30,soil testing,0.0,687.0,6792.0,51.43,48.57,12.76,0.00,26.26
23,2017-06-30,transport,0.0,444.0,6792.0,51.43,48.57,8.24,0.00,16.97
24,2017-09-30,food,0.0,470.0,8332.0,32.81,67.19,10.01,0.00,14.91
25,2017-09-30,healthcare,0.0,477.0,8332.0,32.81,67.19,10.16,0.00,15.13
26,2017-09-30,investing,1292.0,0.0,8332.0,32.81,67.19,0.00,27.53,0.00
27,2017-09-30,programming,2340.0,0.0,8332.0,32.81,67.19,0.00,49.86,0.00
28,2017-09-30,reiki,1061.0,0.0,8332.0,32.81,67.19,0.00,22.61,0.00
29,2017-09-30,shelter,0.0,1178.0,8332.0,32.81,67.19,25.10,0.00,37.36
30,2017-09-30,soil testing,0.0,589.0,8332.0,32.81,67.19,12.55,0.00,18.68
31,2017-09-30,transport,0.0,439.0,8332.0,32.81,67.19,9.35,0.00,13.92
32,2017-12-31,food,0.0,29.0,8303.0,-inf,NaN,NaN,NaN,100.00
33,2017-12-31,healthcare,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN
34,2017-12-31,investing,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN
35,2017-12-31,programming,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN
36,2017-12-31,reiki,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN
37,2017-12-31,shelter,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN
38,2017-12-31,soil testing,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN
39,2017-12-31,transport,NaN,NaN,8303.0,-inf,NaN,NaN,NaN,NaN

In [6]:
ms.plot(s2)

In [7]:
# Summarize by quarter start and by category
s3 = ms.summarize(transactions, freq='QS', by_category=True)
s3

,date,category,income,expense,balance,savings_pc_for_period,spending_pc_for_period,spending_pc_for_period_and_category,income_pc_for_period_and_category,expense_pc_for_period_and_category
0,2017-01-01,food,0,577,2096,41.33,58.67,11.38,0.00,19.39
1,2017-01-01,healthcare,0,508,2096,41.33,58.67,10.02,0.00,17.08
2,2017-01-01,investing,1129,0,2096,41.33,58.67,0.00,22.26,0.00
3,2017-01-01,programming,2516,0,2096,41.33,58.67,0.00,49.62,0.00
4,2017-01-01,reiki,1426,0,2096,41.33,58.67,0.00,28.12,0.00
5,2017-01-01,shelter,0,1089,2096,41.33,58.67,21.48,0.00,36.61
6,2017-01-01,soil testing,0,251,2096,41.33,58.67,4.95,0.00,8.44
7,2017-01-01,transport,0,550,2096,41.33,58.67,10.85,0.00,18.49
8,2017-04-01,food,0,173,4005,42.39,57.61,3.84,0.00,6.67
9,2017-04-01,healthcare,0,639,4005,42.39,57.61,14.19,0.00,24.63
10,2017-04-01,investing,1282,0,4005,42.39,57.61,0.00,28.47,0.00
11,2017-04-01,programming,1906,0,4005,42.39,57.61,0.00,42.33,0.00
12,2017-04-01,reiki,1315,0,4005,42.39,57.61,0.00,29.20,0.00
13,2017-04-01,shelter,0,1010,4005,42.39,57.61,22.43,0.00,38.94
14,2017-04-01,soil testing,0,404,4005,42.39,57.61,8.97,0.00,15.57
15,2017-04-01,transport,0,368,4005,42.39,57.61,8.17,0.00,14.19
16,2017-07-01,food,0,183,6748,51.33,48.67,3.42,0.00,7.04
17,2017-07-01,healthcare,0,310,6748,51.33,48.67,5.80,0.00,11.92
18,2017-07-01,investing,1235,0,6748,51.33,48.67,0.00,23.11,0.00
19,2017-07-01,programming,2511,0,6748,51.33,48.67,0.00,46.99,0.00
20,2017-07-01,reiki,1598,0,6748,51.33,48.67,0.00,29.90,0.00
21,2017-07-01,shelter,0,977,6748,51.33,48.67,18.28,0.00,37.56
22,2017-07-01,soil testing,0,687,6748,51.33,48.67,12.86,0.00,26.41
23,2017-07-01,transport,0,444,6748,51.33,48.67,8.31,0.00,17.07
24,2017-10-01,food,0,499,8303,33.13,66.87,10.63,0.00,15.90
25,2017-10-01,healthcare,0,477,8303,33.13,66.87,10.16,0.00,15.20
26,2017-10-01,investing,1292,0,8303,33.13,66.87,0.00,27.53,0.00
27,2017-10-01,programming,2340,0,8303,33.13,66.87,0.00,49.86,0.00
28,2017-10-01,reiki,1061,0,8303,33.13,66.87,0.00,22.61,0.00
29,2017-10-01,shelter,0,1134,8303,33.13,66.87,24.16,0.00,36.14
30,2017-10-01,soil testing,0,589,8303,33.13,66.87,12.55,0.00,18.77
31,2017-10-01,transport,0,439,8303,33.13,66.87,9.35,0.00,13.99

In [8]:
ms.plot(s3)